service: serverless-telegram-bot

provider:
  name: aws
  runtime: python3.6
  profile:
  environment:
    TELEGRAM_TOKEN: ${file(./serverless.env.yml):TELEGRAM_TOKEN, '1182719709:AAESeaFK2gck6GapJYru_q4vSvADGT5-iGg'}

functions:
  webhook:
    handler: handler.webhook
    events:
      - http: POST /

  set_webhook:
    handler: handler.set_webhook
    events:
      - http: POST /set_webhook

plugins:
  - serverless-python-requirements
